config/routes.rb
RyanMarch::Application.routes.draw do
  root 'pages#home'
  match '/help',      to: 'pages#help',      via: 'get'
  match '/about',     to: 'pages#about',     via: 'get'
  match '/resume',    to: 'pages#resume',    via: 'get'
  match '/contact',   to: 'pages#contact',   via: 'get'
  match '/subscribe', to: 'pages#subscribe', via: 'get'
  match '/starcats',  to: 'pages#starcats',  via: 'get'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def resume
  end

  def about
  end

  def contact
  end

  def subscribe
  end

  def starcats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Site by Ryan March
	</small>
	<nav>
		<ul>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "ryan march", root_path, id: "logo" %>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Home",	     root_path %></li>
						<li><%= link_to "StarCats",  starcats_path %></li>
						<li><%= link_to "Resume",    resume_path %></li>
						<li><%= link_to "Help",      help_path %></li>
						<li><%= link_to "Subscribe", subscribe_path %></li>
					</ul>
				</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecoce.come/svn/trunk/html.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ryan March | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all",
                                            "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<% provide(:header, '| About') %> 

<h1>About</h1>
<p>
  About me!
</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<% provide(:header, '| Contact') %> 
<p>
  Contact me
</p>

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  The help page for my site
</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:header, '') %> 

<!DOCTYPE html>
<div class="center hero-unit">
	<h1>Welcome to Ryan March</h1>
	<h2>
		This is my home page
	</h2>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/pages/resume.html.erb
<% provide(:title, 'Resume') %>
<% provide(:header, '| Resume') %> 
<p>
  <h1>Current Projects</h1>

  <li><%= link_to "StarCats",  starcats_path %></li>
</p>

app/views/pages/starcats.html.erb
<% provide(:title, 'StarCats') %>
<% provide(:header, '| StarCats') %> 

<h1>StarCats</h1>
<p>
  <h3>About the StarCats</h3>

  Throughout our group history, we have gone through many name changes. We have been called team Slow Cooking, team Serendipity, and team Starcats.<br>
  <br>
  What we are currently working on is a video game for our Senior Projects Course. This will be a PC game written in XNA. Stay tuned! There's more to come.
</p>

app/views/pages/subscribe.html.erb
<% provide(:title, 'Subscribe') %>
<% provide(:header, '| Subscribe') %> 
<p>
  Subscribe to me
</p>